# -*- coding: utf-8 -*-
"""Dspace XML input form's value pair generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12m-ykh3WCYJE8H_TNgq4CglJh2HNR-oT

Script I wrote to generate XML input form value pairs for Dspace customization. It will embed the list in to XML tags.  

Upload a text (txt) file with each entry on a seperate line.
eg: 

You could also try http://staff.lib.muohio.edu/~tzoce/files/dspace/value-pairs.html (It does not not work well with thaana script (Maldivian). Probably an issue with processing)
"""

from google.colab import files

uploaded = files.upload()
# upload a list seperated by lines. 
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

filename = open(fn, "r")
li = filename.read().split('\n') 
li = [x.strip(' ') for x in li] # removes spaces from beggining and end of each name
for y in range(len(li)):
  #creates dspace xml form input tags with list (of names) and shows output to screen.
  displayvalue = "\t<displayed-value>" + li[y].strip() + "</displayed-value> "
  storedvalue = "\t<stored-value>" + li[y] + "</stored-value> "
  print ("<pair>\n" + displayvalue + "\n" + storedvalue + "\n</pair>\n")
  
  #stores the generated list to a text file (useful for longer lists)
  f= open("xml_input_valuepairs.txt","a",)
  f.writelines("<pair>\n" + displayvalue + "\n" + storedvalue + "\n</pair>\n")
f.close()
